#!/usr/bin/env python3
"""Resize logo PNG to RGB565 and emit LVGL 7 lv_img_dsc_t C source."""
from __future__ import annotations

import argparse
import pathlib
import struct
import sys

try:
    from PIL import Image
except ImportError:
    print("Install Pillow: pip install Pillow", file=sys.stderr)
    sys.exit(1)


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("input_png", type=pathlib.Path)
    p.add_argument("out_c", type=pathlib.Path)
    p.add_argument("--size", type=int, default=128, help="Square edge in pixels")
    args = p.parse_args()

    img = Image.open(args.input_png).convert("RGBA")
    img = img.resize((args.size, args.size), Image.Resampling.LANCZOS)

    w, h = img.size
    raw = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b, a = img.getpixel((x, y))
            if a < 255:
                # Blend on white (logo background)
                r = (r * a + 255 * (255 - a)) // 255
                g = (g * a + 255 * (255 - a)) // 255
                b = (b * a + 255 * (255 - a)) // 255
            raw += struct.pack("<H", rgb565(r, g, b))

    data_size = len(raw)
    lines = []
    for i in range(0, len(raw), 16):
        chunk = raw[i : i + 16]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hexes},")

    c = f'''/* Auto-generated by scripts/gen_walker_splash.py — do not edit */
#include "lvgl.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

static const LV_ATTRIBUTE_MEM_ALIGN uint8_t walker_splash_map[] = {{
{chr(10).join(lines)}
}};

const lv_img_dsc_t walker_splash = {{
  .header.cf = LV_IMG_CF_TRUE_COLOR,
  .header.always_zero = 0,
  .header.reserved = 0,
  .header.w = {w},
  .header.h = {h},
  .data_size = {data_size},
  .data = walker_splash_map,
}};
'''
    args.out_c.write_text(c, encoding="utf-8")
    print(f"Wrote {args.out_c} ({w}x{h}, {data_size} bytes)")


if __name__ == "__main__":
    main()
